# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflow.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='workflow.proto',
  package='openworkflow.workflow',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eworkflow.proto\x12\x15openworkflow.workflow\x1a\x1egoogle/protobuf/duration.proto\"\x83\x02\n\x08Workflow\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x10\n\x08schedule\x18\x15 \x01(\t\x12\x12\n\nstart_time\x18\x16 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x17 \x01(\t\x12\x13\n\x0b\x63oncurrency\x18\x19 \x01(\r\x12\x17\n\x0fmax_active_runs\x18\x1a \x01(\r\x12*\n\x07timeout\x18\x1b \x01(\x0b\x32\x19.google.protobuf.Duration\x12*\n\x05Tasks\x18\x1f \x03(\x0b\x32\x1b.openworkflow.workflow.Task\"\x9e\x02\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x61g_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x36\n\tcondition\x18\x04 \x01(\x0e\x32#.openworkflow.workflow.RunCondition\x12\x18\n\x10\x64ownstream_tasks\x18\x05 \x03(\t\x12\x0f\n\x07retries\x18\x06 \x01(\r\x12\x31\n\x0eretry_interval\x18\x07 \x01(\x0b\x32\x19.google.protobuf.Duration\x12J\n\x15\x65xecution_environment\x18\x0b \x01(\x0b\x32+.openworkflow.workflow.ExecutionEnvironment\"\xe1\x01\n\x14\x45xecutionEnvironment\x12:\n\rexecutor_kind\x18\x01 \x01(\x0e\x32#.openworkflow.workflow.ExecutorKind\x12Y\n\x11local_environment\x18\x02 \x01(\x0b\x32<.openworkflow.workflow.ExecutionEnvironment.LocalEnvironmentH\x00\x1a#\n\x10LocalEnvironment\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\tB\r\n\x0b\x65nvironment*l\n\x0cRunCondition\x12\x0c\n\x08\x41LL_DONE\x10\x00\x12\x0c\n\x08ONE_DONE\x10\x01\x12\x0f\n\x0b\x41LL_SUCCESS\x10\x02\x12\x0f\n\x0bONE_SUCCESS\x10\x03\x12\x0e\n\nALL_FAILED\x10\x04\x12\x0e\n\nONE_FAILED\x10\x05*\x19\n\x0c\x45xecutorKind\x12\t\n\x05LOCAL\x10\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])

_RUNCONDITION = _descriptor.EnumDescriptor(
  name='RunCondition',
  full_name='openworkflow.workflow.RunCondition',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL_DONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONE_DONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALL_SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONE_SUCCESS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALL_FAILED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONE_FAILED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=852,
  serialized_end=960,
)
_sym_db.RegisterEnumDescriptor(_RUNCONDITION)

RunCondition = enum_type_wrapper.EnumTypeWrapper(_RUNCONDITION)
_EXECUTORKIND = _descriptor.EnumDescriptor(
  name='ExecutorKind',
  full_name='openworkflow.workflow.ExecutorKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=962,
  serialized_end=987,
)
_sym_db.RegisterEnumDescriptor(_EXECUTORKIND)

ExecutorKind = enum_type_wrapper.EnumTypeWrapper(_EXECUTORKIND)
ALL_DONE = 0
ONE_DONE = 1
ALL_SUCCESS = 2
ONE_SUCCESS = 3
ALL_FAILED = 4
ONE_FAILED = 5
LOCAL = 0



_WORKFLOW = _descriptor.Descriptor(
  name='Workflow',
  full_name='openworkflow.workflow.Workflow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='openworkflow.workflow.Workflow.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='openworkflow.workflow.Workflow.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='openworkflow.workflow.Workflow.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='openworkflow.workflow.Workflow.schedule', index=3,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='openworkflow.workflow.Workflow.start_time', index=4,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='openworkflow.workflow.Workflow.end_time', index=5,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='concurrency', full_name='openworkflow.workflow.Workflow.concurrency', index=6,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_active_runs', full_name='openworkflow.workflow.Workflow.max_active_runs', index=7,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='openworkflow.workflow.Workflow.timeout', index=8,
      number=27, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Tasks', full_name='openworkflow.workflow.Workflow.Tasks', index=9,
      number=31, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=333,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='openworkflow.workflow.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='openworkflow.workflow.Task.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dag_id', full_name='openworkflow.workflow.Task.dag_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='openworkflow.workflow.Task.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition', full_name='openworkflow.workflow.Task.condition', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='downstream_tasks', full_name='openworkflow.workflow.Task.downstream_tasks', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retries', full_name='openworkflow.workflow.Task.retries', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retry_interval', full_name='openworkflow.workflow.Task.retry_interval', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execution_environment', full_name='openworkflow.workflow.Task.execution_environment', index=7,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=622,
)


_EXECUTIONENVIRONMENT_LOCALENVIRONMENT = _descriptor.Descriptor(
  name='LocalEnvironment',
  full_name='openworkflow.workflow.ExecutionEnvironment.LocalEnvironment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='openworkflow.workflow.ExecutionEnvironment.LocalEnvironment.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=800,
  serialized_end=835,
)

_EXECUTIONENVIRONMENT = _descriptor.Descriptor(
  name='ExecutionEnvironment',
  full_name='openworkflow.workflow.ExecutionEnvironment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='executor_kind', full_name='openworkflow.workflow.ExecutionEnvironment.executor_kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_environment', full_name='openworkflow.workflow.ExecutionEnvironment.local_environment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXECUTIONENVIRONMENT_LOCALENVIRONMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='environment', full_name='openworkflow.workflow.ExecutionEnvironment.environment',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=625,
  serialized_end=850,
)

_WORKFLOW.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_WORKFLOW.fields_by_name['Tasks'].message_type = _TASK
_TASK.fields_by_name['condition'].enum_type = _RUNCONDITION
_TASK.fields_by_name['retry_interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_TASK.fields_by_name['execution_environment'].message_type = _EXECUTIONENVIRONMENT
_EXECUTIONENVIRONMENT_LOCALENVIRONMENT.containing_type = _EXECUTIONENVIRONMENT
_EXECUTIONENVIRONMENT.fields_by_name['executor_kind'].enum_type = _EXECUTORKIND
_EXECUTIONENVIRONMENT.fields_by_name['local_environment'].message_type = _EXECUTIONENVIRONMENT_LOCALENVIRONMENT
_EXECUTIONENVIRONMENT.oneofs_by_name['environment'].fields.append(
  _EXECUTIONENVIRONMENT.fields_by_name['local_environment'])
_EXECUTIONENVIRONMENT.fields_by_name['local_environment'].containing_oneof = _EXECUTIONENVIRONMENT.oneofs_by_name['environment']
DESCRIPTOR.message_types_by_name['Workflow'] = _WORKFLOW
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['ExecutionEnvironment'] = _EXECUTIONENVIRONMENT
DESCRIPTOR.enum_types_by_name['RunCondition'] = _RUNCONDITION
DESCRIPTOR.enum_types_by_name['ExecutorKind'] = _EXECUTORKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Workflow = _reflection.GeneratedProtocolMessageType('Workflow', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOW,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:openworkflow.workflow.Workflow)
  })
_sym_db.RegisterMessage(Workflow)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:openworkflow.workflow.Task)
  })
_sym_db.RegisterMessage(Task)

ExecutionEnvironment = _reflection.GeneratedProtocolMessageType('ExecutionEnvironment', (_message.Message,), {

  'LocalEnvironment' : _reflection.GeneratedProtocolMessageType('LocalEnvironment', (_message.Message,), {
    'DESCRIPTOR' : _EXECUTIONENVIRONMENT_LOCALENVIRONMENT,
    '__module__' : 'workflow_pb2'
    # @@protoc_insertion_point(class_scope:openworkflow.workflow.ExecutionEnvironment.LocalEnvironment)
    })
  ,
  'DESCRIPTOR' : _EXECUTIONENVIRONMENT,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:openworkflow.workflow.ExecutionEnvironment)
  })
_sym_db.RegisterMessage(ExecutionEnvironment)
_sym_db.RegisterMessage(ExecutionEnvironment.LocalEnvironment)


# @@protoc_insertion_point(module_scope)
